[project]
name = 'Holographic-Universe-Simulation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-analysis]
path = 'contracts/data-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulation-management]
path = 'contracts/simulation-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.theoretical-model-proposals]
path = 'contracts/theoretical-model-proposals.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
